### ISSUE TITLE
Search results get back in gibberish

### ISSUE THREAD

**Issue by Draxler** [AurousGroup/Bug-Tracker#125] opened 2015-10-12 21:14 UTC
When i put search term JAZZ into search box, i get back results in gibberish.
It seams Aurous can't recognise a lot of ''foraign'' characters and start showing characters at random.

![jazz](https://cloud.githubusercontent.com/assets/7681671/10438938/f138664a-7136-11e5-9f2a-eacfb2cfebc0.PNG)

**Comment by Codeusa** [comment] 2015-10-13 03:01
Assigning to @dmxt because this is a font issue.

**Comment by dmxt** [comment] 2015-10-13 03:41
Encoding related. Not my assignment. 

Andrew confirmed that it's fixed, it should be patched soon.

**Closed** 2015-10-13 03:42 UTC
Labels: bug

**Comment by Codeusa** [comment] 2015-10-13 03:56
Fixed

![fixed](http://i.andrew.im/0gnw8i.png)

**Comment by Draxler** [comment] 2015-10-13 15:14
@Codeusa 

is fix pushed becuase i don't see any changes on my side?

**Comment by anVlad11** [comment] 2015-10-13 17:09
@Draxler @Codeusa can confirm, non-latin characters still looking weird.
