### ISSUE TITLE
Picture isn't showing

### ISSUE THREAD

**Issue by ElGatoSaez** [AurousGroup/Bug-Tracker#42] opened 2015-10-10 17:44 UTC
Picture isn't showing, as seen in this image: 
![image](https://cloud.githubusercontent.com/assets/10396037/10412472/5a26bed0-6f5d-11e5-9229-00ab4daa8ff0.png)

**Comment by srcnalt** [comment] 2015-10-10 17:47
I stated that here #31

**Comment by ElGatoSaez** [comment] 2015-10-10 17:52
Sorry

**Comment by srcnalt** [comment] 2015-10-10 17:53
:0) no probs, just search before submitting an issue.

**Comment by Codeusa** [comment] 2015-10-10 22:11
Duplicate of #31

**Closed by Codeusa** 2015-10-10 22:11 UTC
